// react-frontend/src/components/OrderPage.jsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import styled from "styled-components"; // Import styled-components

// Styled-components
const Container = styled.div`
  min-height: 100vh;
  background-color: #f9fafb;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 2.5rem 0;
`;

const Title = styled.h1`
  font-size: 2.5rem;
  font-weight: bold;
  margin-bottom: 1.5rem;
  color: #1a202c;
`;

const Description = styled.p`
  font-size: 1.125rem;
  text-align: center;
  color: #4a5568;
  margin-bottom: 2rem;
`;

const DashboardButton = styled.button`
  background-color: #edf2f7;
  color: #2d3748;
  padding: 0.75rem 1.5rem;
  border-radius: 0.375rem;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s ease;

  &:hover {
    color: #fafafa;
    background-color: #d40f0f;
  }
`;

const OrderPage = () => {
  const [orderId, setOrderId] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    // Retrieve orderId from localStorage when the component mounts
    const storedOrderId = localStorage.getItem("orderId");
    if (storedOrderId) {
      setOrderId(storedOrderId);
    } else {
      alert("No order found. Please create an order first.");
      navigate("/dashboard");
    }
  }, [navigate]);

  return (
    <Container>
      <Title>Order ID: {orderId}</Title>
      <Description>
        Silakan ke kasir untuk melakukan konfirmasi pesanan Anda. :3
      </Description>

      <DashboardButton onClick={() => navigate("/dashboard")}>
        Dashboard
      </DashboardButton>
    </Container>
  );
};

export default OrderPage;

// frontend/src/components/OrderPage.vue
<template>
  <div
    class="min-h-screen bg-back flex flex-col items-center justify-center py-10"
  >
    <h1 class="text-4xl font-bold mb-4 text-custom">Order ID: {{ orderId }}</h1>
    <p class="text-lg text-center text-description">
      Silakan ke kasir untuk melakukan konfirmasi pesanan Anda. :3
    </p>
  </div>
  <div class="absolute top-5 right-5">
    <router-link to="/home" class="bg-description text-custom px-4 py-2 rounded"
      >Home</router-link
    >
  </div>
</template>

<script>
export default {
  data() {
    return {
      orderId: null,
    };
  },
  mounted() {
    this.orderId = localStorage.getItem("orderId");
  },
};
</script>

<style scoped>
.back {
  background-color: #e5f9f2;
}

.text-custom {
  color: #0b3d3e;
}

.text-description {
  color: #1f1f1f;
}

.bg-description {
  background-color: #b7e3d8;
}
</style>
