// frontend/src/components/ReviewPage.vue
<template>
  <div class="min-h-screen bg-gray-100 flex items-center justify-center">
    <div class="max-w-md w-full bg-white shadow-lg rounded-lg p-8">
      <h1 class="text-2xl font-bold text-center text-custom mb-4">
        Review Order #{{ orderId }}
      </h1>
      <form @submit.prevent="submitReview">
        <div class="mb-4">
          <label class="block text-sm font-medium text-gray-700">Rating:</label>
          <div class="flex space-x-2 mt-1">
            <label v-for="num in 5" :key="num" class="flex items-center">
              <input
                type="radio"
                v-model="rating"
                :value="num"
                class="mr-1"
                required
              />
              <span>{{ num }}</span>
            </label>
          </div>
        </div>
        <div class="mb-4">
          <label for="comment" class="block text-sm font-medium text-gray-700"
            >Comment:</label
          >
          <textarea
            v-model="comment"
            maxlength="255"
            class="mt-1 block w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-green-300"
            rows="4"
            required
          ></textarea>
        </div>
        <button
          type="submit"
          :disabled="loading"
          class="w-full bg-green-800 text-white px-4 py-2 rounded-lg hover:bg-green-900 transition disabled:opacity-50"
        >
          {{ loading ? "Mengirim..." : "Kirim Review" }}
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      orderId: this.$route.params.id,
      rating: "", // Default rating is empty
      comment: "",
      loading: false, // Loading state for submission
    };
  },
  methods: {
    async submitReview() {
      if (!this.rating || !this.comment) {
        alert("Please provide a rating and a comment."); // Validation message
        return;
      }

      this.loading = true;

      try {
        await axios.post(
          `http://localhost:5000/api/orders/${this.orderId}/review`,
          {
            rating: this.rating,
            comment: this.comment,
          },
          {
            headers: {
              Authorization: `Bearer ${localStorage.getItem("token")}`,
            },
          }
        );
        this.showSuccess("Review berhasil dikirim!");
        this.$router.push("/orders-history");
      } catch (error) {
        console.error("Error submitting review:", error);
        alert("Gagal mengirim review.");
      } finally {
        this.loading = false; // Reset loading state
      }
    },
    showSuccess(message) {
      // Replace this with your preferred notification method
      alert(message);
    },
  },
};
</script>

<style scoped>
.text-custom {
  color: #0b3d3e; /* Custom color for headings */
}
</style>

// react-frontend/src/components/ReviewPage.jsx
import React, { useState } from "react";
import axios from "axios";
import { useParams, useNavigate } from "react-router-dom";
import styled from "styled-components";

// Styled-components
const Container = styled.div`
  min-height: 100vh;
  background-color: #f9fafb;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const ReviewCard = styled.div`
  max-width: 400px;
  width: 100%;
  background-color: white;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  border-radius: 8px;
  border: 2px solid red;
  padding: 2rem;
`;

const Title = styled.h1`
  font-size: 1.875rem;
  font-weight: bold;
  text-align: center;
  color: #2d3748;
  margin-bottom: 1.5rem;
`;

const Label = styled.label`
  font-size: 0.875rem;
  font-weight: medium;
  color: #4a5568;
`;

const RatingLabel = styled(Label)`
  font-size: 1rem;
`;

const CommentLabel = styled(Label)`
  font-size: 1rem;
`;

const RatingWrapper = styled.div`
  display: flex;
  gap: 0.5rem;
  margin-top: 0.5rem;
`;

const RadioButton = styled.input`
  margin-right: 0.25rem;
`;

const TextArea = styled.textarea`
  margin-top: 0.5rem;
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #cbd5e0;
  border-radius: 8px;
  resize: none;
  outline: none;
  transition: border-color 0.3s ease;

  &:focus {
    border-color: #68d391;
  }
`;

const SubmitButton = styled.button`
  width: 100%;
  background-color: #2f855a;
  color: white;
  padding: 1rem;
  border-radius: 8px;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s ease;

  &:hover {
    background-color: #38a169;
  }

  &:disabled {
    background-color: #cbd5e0;
    cursor: not-allowed;
  }
`;

const ReviewPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [rating, setRating] = useState("");
  const [comment, setComment] = useState("");
  const [loading, setLoading] = useState(false);

  const submitReview = async (e) => {
    e.preventDefault();

    if (!rating || !comment) {
      alert("Please provide a rating and a comment.");
      return;
    }

    setLoading(true);

    try {
      await axios.post(
        `http://localhost:3000/api/orders/${id}/review`,
        { rating, comment },
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        }
      );
      alert("Review berhasil dikirim!");
      navigate("/orders-history"); // Redirect to orders history
    } catch (error) {
      console.error("Error submitting review:", error);
      alert("Gagal mengirim review.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container>
      <ReviewCard>
        <Title>Review Order #{id}</Title>
        <form onSubmit={submitReview}>
          <div style={{ marginBottom: "1rem" }}>
            <RatingLabel>Rating:</RatingLabel>
            <RatingWrapper>
              {[1, 2, 3, 4, 5].map((num) => (
                <label key={num} className="flex items-center">
                  <RadioButton
                    type="radio"
                    value={num}
                    checked={rating === num.toString()}
                    onChange={() => setRating(num.toString())}
                    required
                  />
                  <span>{num}</span>
                </label>
              ))}
            </RatingWrapper>
          </div>
          <div style={{ marginTop: "1rem" }}>
            <CommentLabel>Comment:</CommentLabel>
            <TextArea
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              maxLength="255"
              rows="4"
              required
            />
          </div>
          <SubmitButton type="submit" disabled={loading}>
            {loading ? "Mengirim..." : "Kirim Review"}
          </SubmitButton>
        </form>
      </ReviewCard>
    </Container>
  );
};

export default ReviewPage;
